server.port=8081
spring.application.name=fiosmj-app
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
mercadopago.access-token=APP_USR-4475499951270269-032311-8fdc352e14aeec95ca2cf584e222e615-772071256
mercadopago.public-key=APP_USR-518808ef-1627-44b4-a82f-cc4f393ff361
